version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npm t

  deploy:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: git config --global user.email "lipilin.m@gmail.com"
      - run: git config --global user.name "Mikhail Lipilin"
      - run: npm deploy-storybook

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
